---
format_version: '23'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
trigger_map:
- tag: v*
  pipeline: build-publish
workflows:
  build-ios-binaries:
    summary: Build iOS binaries
    description: Installs dependencies and builds DuckDB native libraries for iOS.
    steps:
    - git-clone:
        inputs:
        - fetch_tags: 'yes'
    - script:
        title: Install Dependencies (Ninja, CMake, vcpkg)
        inputs:
        - content: |
            #!/bin/bash
            set -e
            echo "Installing Ninja and CMake..."
            brew install ninja cmake

            echo "Installing vcpkg..."
            git clone https://github.com/Microsoft/vcpkg.git $HOME/vcpkg
            $HOME/vcpkg/bootstrap-vcpkg.sh

            # Expose VCPKG_ROOT for subsequent steps
            envman add --key VCPKG_ROOT --value "$HOME/vcpkg"
    - script:
        title: Build iOS Binaries
        inputs:
        - content: |
            #!/bin/bash
            set -e
            # Ensure VCPKG_ROOT is set
            export VCPKG_ROOT="$HOME/vcpkg"

            echo "Building iOS binaries (monolithic with all extensions)..."
            ./scripts/build-ios.sh
    - script:
        title: Zip iOS Artifacts
        inputs:
        - content: |
            #!/bin/bash
            set -e
            cd ios/Frameworks
            zip -r $BITRISE_DEPLOY_DIR/DuckDB.xcframework.zip DuckDB.xcframework
    - deploy-to-bitrise-io:
        inputs:
        - pipeline_intermediate_files: "$BITRISE_DEPLOY_DIR/DuckDB.xcframework.zip:IOS_FRAMEWORK_ZIP_PATH"
  build-android-binaries:
    summary: Build Android binaries
    description: Installs dependencies and builds DuckDB native libraries for Android.
    steps:
    - git-clone:
        inputs:
        - fetch_tags: 'yes'
    - script:
        title: Install Dependencies (Ninja, CMake, vcpkg)
        inputs:
        - content: |
            #!/bin/bash
            set -e
            echo "Installing Ninja, CMake, pkg-config, and autoconf tools..."
            sudo apt-get update && sudo apt-get install -y ninja-build cmake pkg-config autoconf automake libtool

            echo "Installing vcpkg..."
            git clone https://github.com/Microsoft/vcpkg.git $HOME/vcpkg
            $HOME/vcpkg/bootstrap-vcpkg.sh

            # Expose VCPKG_ROOT for subsequent steps
            envman add --key VCPKG_ROOT --value "$HOME/vcpkg"
    - script:
        title: Build Android Binaries
        inputs:
        - content: |
            #!/bin/bash
            set -e
            # Ensure VCPKG_ROOT is set
            export VCPKG_ROOT="$HOME/vcpkg"

            echo "Building Android binaries (monolithic with all extensions)..."
            ./scripts/build-android.sh
    - script:
        title: Zip Android Artifacts
        inputs:
        - content: |
            #!/bin/bash
            set -e
            cd android/src/main/jniLibs
            zip -r $BITRISE_DEPLOY_DIR/android-libs.zip .
    - deploy-to-bitrise-io:
        inputs:
        - pipeline_intermediate_files: "$BITRISE_DEPLOY_DIR/android-libs.zip:ANDROID_LIBS_ZIP_PATH"
    meta:
      bitrise.io:
        stack: ubuntu-noble-24.04-bitrise-2025-android
        machine_type_id: elite
  build-npm-package:
    summary: Package and Publish
    description: Downloads artifacts, packs the NPM package, and publishes to NPM
      and GitHub Releases.
    steps:
    - git-clone:
        inputs:
        - fetch_tags: 'yes'
    - pull-intermediate-files: {}
    - script:
        title: Restore Artifacts
        inputs:
        - content: |
            #!/bin/bash
            set -e

            echo "Restoring iOS binaries from $IOS_FRAMEWORK_ZIP_PATH..."
            # Ensure destination exists
            mkdir -p ios/Frameworks
            unzip -qo "$IOS_FRAMEWORK_ZIP_PATH" -d ios/Frameworks

            echo "Restoring Android binaries from $ANDROID_LIBS_ZIP_PATH..."
            # Ensure destination exists
            mkdir -p android/src/main/jniLibs
            unzip -qo "$ANDROID_LIBS_ZIP_PATH" -d android/src/main/jniLibs
    - script:
        title: Authenticate with NPM
        inputs:
        - content: |
            #!/bin/bash
            set -e
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - script:
        title: Build and Pack
        inputs:
        - content: |
            #!/bin/bash
            set -e

            echo "Syncing package.json version with git tag..."
            if [[ -n "$BITRISE_GIT_TAG" ]]; then
                # Strip 'v' prefix if present
                VERSION_NUM="${BITRISE_GIT_TAG#v}"
                npm version $VERSION_NUM --no-git-tag-version
            fi

            echo "Installing NPM dependencies..."
            SKIP_BINARY_DOWNLOAD=true npm install

            echo "Building TypeScript..."
            npm run build

            echo "Packing NPM package..."
            npm pack

            # Find the generated tarball
            PKG_FILE=$(ls *.tgz | head -n 1)

            # Move the tarball to the deploy directory
            mv "$PKG_FILE" "$BITRISE_DEPLOY_DIR/"

            # Expose the full path for the next step
            envman add --key RELEASE_ARCHIVE_PATH --value "$BITRISE_DEPLOY_DIR/$PKG_FILE"
    - script:
        title: Publish to NPM
        inputs:
        - content: |
            #!/bin/bash
            set -e
            # Only publish if we are on a tag
            if [[ -n "$BITRISE_GIT_TAG" ]]; then
                echo "Publishing version $BITRISE_GIT_TAG to NPM..."
                npm publish --access public
            else
                echo "Not a tagged build, skipping NPM publish."
            fi
    - github-release:
        inputs:
        - api_token: "$GITHUB_ACCESS_TOKEN"
        - username: "$GITHUB_USERNAME"
        - repository_url: https://github.com/bangonkali/capacitor-duckdb
        - tag: "$BITRISE_GIT_TAG"
        - name: "$BITRISE_GIT_TAG"
        - body: Automated release from Bitrise build $BITRISE_BUILD_NUMBER
        - draft: 'no'
        - files_to_upload: |-
            $RELEASE_ARCHIVE_PATH
            $IOS_FRAMEWORK_ZIP_PATH
            $ANDROID_LIBS_ZIP_PATH
    meta:
      bitrise.io:
        stack: ubuntu-noble-24.04-bitrise-2025-android
        machine_type_id: elite
pipelines:
  build-publish:
    workflows:
      build-ios-binaries: {}
      build-android-binaries: {}
      build-npm-package:
        depends_on:
        - build-ios-binaries
        - build-android-binaries
meta:
  bitrise.io:
    stack: osx-xcode-16.4.x
    machine_type_id: g2.mac.large
